server:
  port: 8080

spring:
  application:
    name: workflow
  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update

flowable:
  database-schema-update: true
  check-process-definitions: true
  async-executor-activate: false
