# Local connections
local   all             all                                 trust

# IPv4 local connections
host    all             all             127.0.0.1/32        trust

# Docker network
host    all             all             0.0.0.0/0           scram-sha-256

# Replication
host    replication     replicator      0.0.0.0/0           scram-sha-256