listen_addresses = '*' #by default listen to localhost

wal_level = replica #provide enough wal info for replica
max_wal_senders = 10 #resplication connection at a time
max_replication_slots = 10 #keep track of up to 10 independent replica

hot_standby = on #Allows a replica to answer read-only queries while replaying WAL

synchronous_standby_names = 'FIRST 1 (replica1)'